name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
        
    - name: Build Docker image
      run: docker build ./client --file ./client/Dockerfile.dev --tag my-image-name:$(date +%s)
      
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USER}}/bootcamp-multi-docker
